CREATE TABLE [ServiceMessage].[ServicePage] (
	[Id]					INT IDENTITY(1,1)				NOT NULL,
	[DisplayName]			NVARCHAR(MAX)					NOT NULL,
	[ControllerName]		NVARCHAR(MAX)					NOT NULL
	
    CONSTRAINT [PK_ServicePage] PRIMARY KEY CLUSTERED ( [Id] ASC )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, DATA_COMPRESSION = PAGE)
)

GO