:r .\Collections_ReferenceData\Pre\CreateTempTables.sql
:r .\Collections_ReferenceData\Scripts\NcsOutcomeRates.sql
:r .\Collections_ReferenceData\Scripts\DevolvedPostcodesPublication.sql
:r .\Collections_ReferenceData\Scripts\2021-MidYear.sql
:r .\Collections_ReferenceData\Scripts\OP-2021-MidYear-FundingClaimsDataExtract-Report.sql
:r .\Collections_ReferenceData\Scripts\OP-2021-MidYear-FundingClaimsProviderSubmission-Report.sql
:r .\Collections_ReferenceData\Scripts\OP-2021-MidYear-FundingClaimsSavedButNotSubmitted-Report.sql
:r .\Collections_ReferenceData\Scripts\OP-2021-YearEnd-FundingClaimsDataExtract-Report.sql
:r .\Collections_ReferenceData\Scripts\OP-2021-YearEnd-FundingClaimsSavedButNotSubmitted-Report.sql
:r .\Collections_ReferenceData\Scripts\OP-2021-YearEnd_FC_ProvSubReport.sql
:r .\Collections_ReferenceData\Scripts\REF-EDRS.sql
:r .\Collections_ReferenceData\Scripts\NCS2122.sql
:r .\Collections_ReferenceData\Scripts\FEW2021.sql
:r .\Collections_ReferenceData\Scripts\EAS2122.sql
:r .\Collections_ReferenceData\Scripts\ILR2122.sql
:r .\Collections_ReferenceData\Scripts\ILRValidationMessages2122.sql
:r .\Collections_ReferenceData\Scripts\FISReferenceData2122.sql
:r .\Collections_ReferenceData\Scripts\REF-ILRLookup2122.sql
:r .\Collections_ReferenceData\Scripts\PE-ACT-Count-Report2122.sql
:r .\Collections_ReferenceData\Scripts\PE-App-Summarisation2122.sql
:r .\Collections_ReferenceData\Scripts\PE-Collection-Stats2122.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-AppsAdditionalPaymentsReport2122.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-AppsCoInvestmentContributionsReport2122.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-AppsDataMatchMonthEndReport2122.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-AppsInternalDataMatchMonthEndReport2122.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-AppsMonthlyPaymentReport2122.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-CrossYearPaymentsReport2122.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-FundingSummaryPeriodEndReport2122.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-PeriodEndReportPreparation2122.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-Reports-Finished2122.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-Run2122.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-Start2122.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-Stop2122.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-Submission2122.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-SubmissionWindowPeriodValidation2122.sql
:r .\Collections_ReferenceData\Scripts\PE-DataExtract-Report2122.sql
:r .\Collections_ReferenceData\Scripts\PE-DataQuality-Report2122.sql
:r .\Collections_ReferenceData\Scripts\PE-Data-Warehouse12122.sql
:r .\Collections_ReferenceData\Scripts\PE-Data-Warehouse22122.sql
:r .\Collections_ReferenceData\Scripts\PE-DC-Summarisation2122.sql
:r .\Collections_ReferenceData\Scripts\PE-ESFANonContDevolvedAdultEducationReport2122.sql
:r .\Collections_ReferenceData\Scripts\PE-ESF-Summarisation2122.sql
:r .\Collections_ReferenceData\Scripts\PE-MCA-Reports2122.sql
:r .\Collections_ReferenceData\Scripts\PE-Metrics-Report2122.sql
:r .\Collections_ReferenceData\Scripts\PE-ProviderSubmissions-Report2122.sql
:r .\Collections_ReferenceData\Scripts\PE-StandardFile2122.sql
:r .\Collections_ReferenceData\Scripts\PE-UYP-LLVReport2122.sql
:r .\Collections_ReferenceData\Scripts\1819-Final.sql
:r .\Collections_ReferenceData\Scripts\1819-YearEnd.sql
:r .\Collections_ReferenceData\Scripts\1920-Final.sql
:r .\Collections_ReferenceData\Scripts\1920-MidYear.sql
:r .\Collections_ReferenceData\Scripts\2021-YearEnd.sql
:r .\Collections_ReferenceData\Scripts\ALLF.sql
:r .\Collections_ReferenceData\Scripts\CampusIdentifier.sql
:r .\Collections_ReferenceData\Scripts\CoFRemoval.sql
:r .\Collections_ReferenceData\Scripts\COVID19.sql
:r .\Collections_ReferenceData\Scripts\COVIDRelief2.sql
:r .\Collections_ReferenceData\Scripts\DEA-Reports1819.sql
:r .\Collections_ReferenceData\Scripts\DevolvedContracts.sql
:r .\Collections_ReferenceData\Scripts\DevolvedPostcodes-FullName.sql
:r .\Collections_ReferenceData\Scripts\DevolvedPostcodes-LocalAuthority.sql
:r .\Collections_ReferenceData\Scripts\DevolvedPostcodes-OnsOverride.sql
:r .\Collections_ReferenceData\Scripts\DevolvedPostcodes-Sof.sql
:r .\Collections_ReferenceData\Scripts\EAS1819.sql
:r .\Collections_ReferenceData\Scripts\EAS1920.sql
:r .\Collections_ReferenceData\Scripts\EAS2021.sql
:r .\Collections_ReferenceData\Scripts\ESF-Reprofiling.sql
:r .\Collections_ReferenceData\Scripts\EsfEligibility.sql
:r .\Collections_ReferenceData\Scripts\ESFR1.sql
:r .\Collections_ReferenceData\Scripts\ESFR2-1819.sql
:r .\Collections_ReferenceData\Scripts\ESFR2-1920.sql
:r .\Collections_ReferenceData\Scripts\ESFR2-2021.sql
:r .\Collections_ReferenceData\Scripts\ESFR2-2122.sql
:r .\Collections_ReferenceData\Scripts\FISReferenceData2021.sql
:r .\Collections_ReferenceData\Scripts\FRM-Reports1920.sql
:r .\Collections_ReferenceData\Scripts\FRM-Reports2021.sql
:r .\Collections_ReferenceData\Scripts\ILR1819.sql
:r .\Collections_ReferenceData\Scripts\ILR1920.sql
:r .\Collections_ReferenceData\Scripts\ILR2021.sql
:r .\Collections_ReferenceData\Scripts\ILRValidationMessages1920.sql
:r .\Collections_ReferenceData\Scripts\ILRValidationMessages2021.sql
:r .\Collections_ReferenceData\Scripts\MCAFundedAims.sql
:r .\Collections_ReferenceData\Scripts\NCS1920.sql
:r .\Collections_ReferenceData\Scripts\NCS2021.sql
:r .\Collections_ReferenceData\Scripts\OnsPostcodes.sql
:r .\Collections_ReferenceData\Scripts\OP-FundingClaimsExtractData1920-Report.sql
:r .\Collections_ReferenceData\Scripts\OP-FundingClaimsProviderSubmission1920-Report.sql
:r .\Collections_ReferenceData\Scripts\OP-ILRFileSubmissionsPerDay-Report1920.sql
:r .\Collections_ReferenceData\Scripts\OP-ILRFileSubmissionsPerDay-Report2021.sql
:r .\Collections_ReferenceData\Scripts\OP-ILRProvidersReturningFirstTimePerDay-Report1920.sql
:r .\Collections_ReferenceData\Scripts\OP-ILRProvidersReturningFirstTimePerDay-Report2021.sql
:r .\Collections_ReferenceData\Scripts\OP-Validation-Report.sql
:r .\Collections_ReferenceData\Scripts\Organisations.sql
:r .\Collections_ReferenceData\Scripts\PE-ACT-Count-Report1920.sql
:r .\Collections_ReferenceData\Scripts\PE-ACT-Count-Report2021.sql
:r .\Collections_ReferenceData\Scripts\PE-ALLF-Summarisation.sql
:r .\Collections_ReferenceData\Scripts\PE-App-Summarisation1819.sql
:r .\Collections_ReferenceData\Scripts\PE-App-Summarisation1920.sql
:r .\Collections_ReferenceData\Scripts\PE-App-Summarisation2021.sql
:r .\Collections_ReferenceData\Scripts\PE-Collection-Stats1920.sql
:r .\Collections_ReferenceData\Scripts\PE-Collection-Stats2021.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-AppsAdditionalPaymentsReport1920.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-AppsAdditionalPaymentsReport2021.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-AppsCoInvestmentContributionsReport1920.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-AppsCoInvestmentContributionsReport2021.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-AppsDataMatchMonthEndReport1920.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-AppsDataMatchMonthEndReport2021.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-AppsInternalDataMatchMonthEndReport1920.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-AppsInternalDataMatchMonthEndReport2021.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-AppsMonthlyPaymentReport1920.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-AppsMonthlyPaymentReport2021.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-CrossYearPaymentsReport2021.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-FundingSummaryPeriodEndReport1920.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-FundingSummaryPeriodEndReport2021.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-PeriodEndReport1819.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-PeriodEndReportPreparation1920.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-PeriodEndReportPreparation2021.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-Reports-Finished1920.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-Reports-Finished2021.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-Run1819.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-Run1920.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-Run2021.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-Start1819.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-Start1920.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-Start2021.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-Stop1819.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-Stop1920.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-Stop2021.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-Submission1819.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-Submission1920.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-Submission2021.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-SubmissionWindowPeriodValidation1920.sql
:r .\Collections_ReferenceData\Scripts\PE-DAS-SubmissionWindowPeriodValidation2021.sql
:r .\Collections_ReferenceData\Scripts\PE-Data-Warehouse11920.sql
:r .\Collections_ReferenceData\Scripts\PE-Data-Warehouse12021.sql
:r .\Collections_ReferenceData\Scripts\PE-Data-Warehouse21920.sql
:r .\Collections_ReferenceData\Scripts\PE-Data-Warehouse22021.sql
:r .\Collections_ReferenceData\Scripts\PE-DataExtract-Report1920.sql
:r .\Collections_ReferenceData\Scripts\PE-DataExtract-Report2021.sql
:r .\Collections_ReferenceData\Scripts\PE-DataQuality-Report1920.sql
:r .\Collections_ReferenceData\Scripts\PE-DataQuality-Report2021.sql
:r .\Collections_ReferenceData\Scripts\PE-DC-Summarisation1819.sql
:r .\Collections_ReferenceData\Scripts\PE-DC-Summarisation1920.sql
:r .\Collections_ReferenceData\Scripts\PE-DC-Summarisation2021.sql
:r .\Collections_ReferenceData\Scripts\PE-ESF-Summarisation1819.sql
:r .\Collections_ReferenceData\Scripts\PE-ESF-Summarisation1920.sql
:r .\Collections_ReferenceData\Scripts\PE-ESF-Summarisation2021.sql
:r .\Collections_ReferenceData\Scripts\PE-ESFANonContDevolvedAdultEducationReport1920.sql
:r .\Collections_ReferenceData\Scripts\PE-ESFANonContDevolvedAdultEducationReport2021.sql
:r .\Collections_ReferenceData\Scripts\PE-MCA-Reports1920.sql
:r .\Collections_ReferenceData\Scripts\PE-MCA-Reports2021.sql
:r .\Collections_ReferenceData\Scripts\PE-NCS-DataExtract-Report2021.sql
:r .\Collections_ReferenceData\Scripts\PE-NCS-DataExtract-Report2122.sql
:r .\Collections_ReferenceData\Scripts\PE-NCS-Summarisation2021.sql
:r .\Collections_ReferenceData\Scripts\PE-NCS-Summarisation2122.sql
:r .\Collections_ReferenceData\Scripts\PE-ProviderSubmissions-Report1920.sql
:r .\Collections_ReferenceData\Scripts\PE-ProviderSubmissions-Report2021.sql
:r .\Collections_ReferenceData\Scripts\PE-StandardFile1920.sql
:r .\Collections_ReferenceData\Scripts\PE-StandardFile2021.sql
:r .\Collections_ReferenceData\Scripts\PE-UYP-LLVReport1920.sql
:r .\Collections_ReferenceData\Scripts\PE-UYP-LLVReport2021.sql
:r .\Collections_ReferenceData\Scripts\ProviderPostcodeSpecialistResources.sql
:r .\Collections_ReferenceData\Scripts\REF-EPA.sql
:r .\Collections_ReferenceData\Scripts\REF-ESF.sql
:r .\Collections_ReferenceData\Scripts\REF-FCS.sql
:r .\Collections_ReferenceData\Scripts\REF-LARS.sql
:r .\Collections_ReferenceData\Scripts\REF-LARSIndex.sql
:r .\Collections_ReferenceData\Scripts\REF-OPS.sql
:r .\Collections_ReferenceData\Scripts\REF-ULN.sql
:r .\Collections_ReferenceData\Scripts\ShortTermFundingInitiatives.sql
:r .\Collections_ReferenceData\Scripts\PE-Metrics-Report1819.sql
:r .\Collections_ReferenceData\Scripts\PE-Metrics-Report1920.sql
:r .\Collections_ReferenceData\Scripts\PE-Metrics-Report2021.sql
:r .\Collections_ReferenceData\Scripts\_Common.sql
:r .\Collections_ReferenceData\Post\Merge_Collection.sql
:r .\Collections_ReferenceData\Post\Merge_ReturnPeriod.sql
:r .\Collections_ReferenceData\Post\Merge_JobTopicTaskSubscription.sql
:r .\Collections_ReferenceData\Post\Merge_JobEmailTemplate.sql
:r .\Collections_ReferenceData\Post\Merge_CollectionRelatedLink.sql
:r .\Collections_ReferenceData\Post\Merge_ScheduleJobs.sql
:r .\Collections_ReferenceData\Post\Merge_ValidityPeriods.sql
:r .\Collections_ReferenceData\Post\Merge_JobMessageKey.sql
:r .\Collections_ReferenceData\Overrides\ValidityPeriod_Overrides.sql
